Fix: latestMessageData -> latestMessage
Chatting-App-FE/Chatting-App-FE pull request #29
Opened 2023-11-11 14:50 UTC by Gaoridang

## ⛳️개요
일단 급하게 develop 브랜치 런타임 에러 해결

2023-11-11 15:10 UTC, SKY-PEY approved these changes
안 그래도 이부분 필요했는데 감사합니다

2023-11-12 06:00 UTC, gahyuun requested changes
늦게까지 작업하시느라 수고했습니다!!

2023-11-12 06:00 UTC, gahyuun commented on src/api/channel.ts
> +  const chatsData = await response.data.chats;
response.data.chats 앞에 await 키워드를 붙이신 이유가 있을까요??

2023-11-12 06:00 UTC, gahyuun commented on src/components/channel/modal/ChannelModalUserList.tsx
set을 써서 O(n)에서 O(1)로 변경하셨네요!

chakra checkbox를 사용하면 여러 항목 선택하는 기능을 아래 기능들을 구현하지 않아도 가능할 것 같은데 직접 구현하신 이유가 있으실까요!?
```
  useEffect(() => {
    setUsers(Array.from(userSet));
  }, [userSet]);

  const isIncluded = (id: string) => {
    return userSet.has(id);
  };
```

2023-11-12 06:00 UTC, gahyuun commented on src/components/channel/modal/CreateChannelModal.tsx
>    const [channel, setChannel] = useRecoilState(channelState);
여기서 recoil 사용하신 이유를 여쭤봐도 될까요??

2023-11-12 06:52 UTC, gahyuun approved these changes

2023-11-12 07:27 UTC, SKY-PEY commented on src/api/channel.ts
> +  const chatsData = await response.data.chats;
앗 이거는 제 코드 같네요! 필요없는 것 같으니 지워놓겠습니다ㅎㅎ

2023-11-12 08:15 UTC, Gaoridang commented on src/components/channel/modal/ChannelModalUserList.tsx
혹시 이부분 좀 더 자세히 설명해주실 수 있나요?? 말씀하신 곳 어떤 부분에서 성능 저하가 있을지 잘 모르겠어서,,

2023-11-12 08:21 UTC, Gaoridang commented on src/components/channel/modal/CreateChannelModal.tsx
>    const [channel, setChannel] = useRecoilState(channelState);
`CategoryRadio` 컴포넌트에서 위 컴포넌트에서 사용하는 `channel.category`를 변경해야 하는데 set 함수를 두 번 props로 내려줘야 해서 recoil을 사용했습니다.

2023-11-12 13:15 UTC, gahyuun commented on src/components/channel/modal/ChannelModalUserList.tsx
Set을 썼을 때에는 큰 성능 저하는 없을 것 같은데요!
컴포넌트 관점에서 봤을 때 Input의 Checkbox 타입을 이용해서 다중 선택을 구현하는 것이 일반적인데 따로 체크박스 로직을 구현하신 이유가 궁금했습니다!

2023-11-12 15:07 UTC, Gaoridang commented on src/components/channel/modal/ChannelModalUserList.tsx
아아~~ 차크라UI 체크박스 컴포넌트에서 체크박스를 삭제하는 방법을 모르겠어서 직접 만들었어요!

2023-11-13 13:03 UTC, merged